version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=library_db
      - DB_USER=postgres
      - DB_PASSWORD=admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
